### ISSUE TITLE
[React Native] [1.1.0-beta.8] `main` module field that could not be resolved

### ISSUE THREAD

**Issue by beetlebum** [vercel/swr#1614]
error: Error: While trying to resolve module `swr` from file `/project/src/core/api/common/ApiConfig.tsx`, the package `/project/node_modules/swr/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/project/node_modules/swr/dist/index.mjs`. Indeed, none of these files exist:

  * /project/node_modules/swr/dist/index.mjs(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /project/node_modules/swr/dist/index.mjs/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/project/node_modules/metro/src/node-haste/DependencyGraph.js:311:17)
    at Object.resolve (/project/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 0)
    at async processModule (/project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:198:5)

**Comment by huozhi** [comment]
Looks like metro currently doesn't support `.mjs` as source file extension
https://github.com/facebook/metro/issues/535
