### ISSUE TITLE
Bug in `createCacheHelper`

### ISSUE THREAD

**Issue by siddharth-leap** [vercel/swr#2771]
# Bug report

I am using `useInfiniteSWR` in a react SDK I have built. Everything works as expected in the development server. But when I use the production build of the SDK I am getting the following error

```txt
TypeError: Cannot read properties of undefined (reading '6')
    at Ye (index.es.js:6095:1)
    at eval (index.es.js:6468:1)
    at useSWRArgs (index.mjs:642:1)
    # other lines....
```

I dug deeper into this and found out that the `infinite` middleware in 'swr/infinite' library file uses `createCacheHelper` function. This function returns an array of 4 objects, of which the third object is a subscriber. This subscriber comes from `state[6]` where state is obtained from `SWRGlobalState.get(cache)`.

The `cache` here is passed into the `createCacheHelper` as the first argument by the infinite middleware.

## Description / Observed Behavior

This is causing my app to crash.

## Expected Behavior

App should not crash.

## Additional Context

SWR version - 2.2.2

<img width="100%" alt="Screenshot 2023-09-05 at 4 04 17 PM" src="https://github.com/vercel/swr/assets/114133109/de8372bc-e016-4956-8756-9d13f90ff78f">

<img width="100%" alt="createCacheHelper file" src="https://github.com/vercel/swr/assets/114133109/2525f736-1d63-4a1a-93e8-0a8025f723a9">

<img width="100%" alt="swr/infinite file" src="https://github.com/vercel/swr/assets/114133109/71c94208-ec0d-4dda-91b4-a59b7932fa5d">

**Comment by EduardoSimon** [comment]
I have the same issue. So far, I have detected that the `SWRGlobalState` gets deleted somehow.

**Comment by gkiely** [comment]
I can recreate this reliably. Will set up a repro when I get time.
<img width="626" alt="image" src="https://github.com/user-attachments/assets/7f6b06bc-61df-45ba-8cc8-4be2b514b785">

**Comment by elie222** [comment]
Facing the same issue :(
`Cannot read properties of undefined (reading '6')`

Only impacts certain users for some reason.

**Comment by ranisalt** [comment]
Frustrating this has gone completely ignored for over a year :( since everything is async, it's really hard to figure out what requests are being fired and not finished

**Comment by lsanwick** [comment]
Any chance we someone can look into this further? The logic in [helper.ts](https://github.com/vercel/swr/blob/0b3c2c757d9ce4f7e386a925f695adf93cf9065c/src/_internal/utils/helper.ts#L18) seems incorrect, as it's typecasting away the case where `state` is `undefined`, which is exactly what's happening in this situation.

**Comment by JoshJRennie** [comment]
We had this issue only in our tests since we were using `provider: () => new Map()` whereas our production code didn't use a provider. We hacked around it by doing this:
```
provider: (defaultCache) => {
    const defaultGlobalState = SWRGlobalState.get(defaultCache);
    const newCache = new Map();

    if (defaultGlobalState) {
        SWRGlobalState.set(newCache, defaultGlobalState);
    }

    return newCache;
}
```

**Comment by JoshJRennie** [comment]
We had this issue only in our tests since we were using `provider: () => new Map()` to reset the cache between tests whereas our production code wasn't passing a provider. We hacked around it by doing the following
```
import { initCache } from "swr/_internal";
...
provider: () => {
    const newMap = new Map();
    initCache(newMap);
    return newMap;
}
```
