### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'visibilityState')

### ISSUE THREAD

**Issue by hiromaily** [vercel/swr#2784]
# Bug report

The following error sometimes occurs under jest environment. But not always happens

```
TypeError: Cannot read properties of undefined (reading 'visibilityState')
    at Object.isVisible (/Users/project/app/node_modules/swr/_internal/dist/index.js:140:59)
    at isActive (/Users/project/app/node_modules/swr/core/dist/index.js:55:38)
    at /Users/project/app/node_modules/swr/core/dist/index.js:330:29
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Description / Observed Behavior

Same to Bug report

## Expected Behavior

no error

## Repro Steps / Code Example
```
  export const SWRNoCacheConfig = ({ children }: { children: ReactNode }) => (
    <SWRConfig value={{ provider: () => new Map() }}>{children}</SWRConfig>
  );

  const { result } = renderHook(
    () => useMyHook(),
    {
      wrapper: SWRNoCacheConfig,
    },
  );
```

## Additional Context
swr version is 2.2.2 plus using react

```
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "swr": "^2.2.2",
```

**Comment by koba04** [comment]
duplicated of #2373
