### ISSUE TITLE
TypeError: swr__WEBPACK_IMPORTED_MODULE_14___default is not a function

### ISSUE THREAD

**Issue by lucafaggianelli** [vercel/swr#419]
I'm using SWR in a page as documented:

```js
import useSWR from 'swr'

export default function Dashboard () {
  const [ entries, error ] = useSWR(`/api/reports/${router.query.id}`)

  if (error) return <div>failed to load projects</div>
  if (!entries) return <div>loading...</div>
  // render something
}
```

but I receive this error: `TypeError: swr__WEBPACK_IMPORTED_MODULE_14___default is not a function`

It's worth noting that I'm using SWR also in `_app.js` file to populate a menu and it's working.

My setup:
```
"next": "9.4.4",
"react": "16.13.1",
"react-dom": "16.13.1",
"swr": "^0.2.2"
```

Here the full trace:

```
nodeStackFrames.js:39 Uncaught     at Dashboard (file://C:\Users\Luca.faggianelli\dev\bnd-client\.next\server\static\development\pages\projects\id.js:2043:28)
    at processChild (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at render (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\next\dist\next-server\server\render.js:3:298)
    at renderPage (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\next\dist\next-server\server\render.js:46:1020)
    at Object.ctx.renderPage (file://C:\Users\Luca.faggianelli\dev\bnd-client\.next\server\static\development\pages\_document.js:1003:26)
    at Function.getInitialProps (file://C:\Users\Luca.faggianelli\dev\bnd-client\.next\server\static\development\pages\_document.js:309:19)
    at Function.module.exports../pages/_document.js.MyDocument.getInitialProps (file://C:\Users\Luca.faggianelli\dev\bnd-client\.next\server\static\development\pages\_document.js:1014:83)
    at loadGetInitialProps (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\next\dist\next-server\lib\utils.js:5:101)
    at renderToHTML (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\next\dist\next-server\server\render.js:46:1330)
    at async (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\next\dist\next-server\server\next-server.js:68:285)
    at async (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\next\dist\next-server\server\next-server.js:67:142)
    at async DevServer.renderToHTMLWithComponents (file://C:\Users\Luca.faggianelli\dev\bnd-client\node_modules\next\dist\next-server\server\next-server.js:91:254)
```

**Comment by huozhi** [comment]
@lucafaggianelli swr hook returns an object from hook instead of array. try

```diff
export default function Dashboard () {
-  const [ entries, error ] = useSWR(`/api/reports/${router.query.id}`)
+  const { data: entries, error } = useSWR(`/api/reports/${router.query.id}`)
}
```

**Comment by lucafaggianelli** [comment]
Ah damn sure! Thank you so much, I don't know why I have half calls with an array and half with an object, that was the issue
