### ISSUE TITLE
Test suite of focusThrottleInterval fails very often

### ISSUE THREAD

**Issue by huozhi** [vercel/swr#940]
# Issue report

## Description

What kind of issues did you encounter with SWR?

swr test case for `focusThrottleInterval` fails very often

```sh
Run yarn test
yarn run v1.22.5
$ jest
PASS test/use-swr-local-mutation.test.tsx
PASS test/use-swr-infinite.test.tsx
PASS test/use-swr-refresh.test.tsx (6.795s)
PASS test/use-swr-integration.test.tsx
PASS test/use-swr-error.test.tsx
PASS test/use-swr-config-callbacks.test.tsx
PASS test/use-swr-suspense.test.tsx
PASS test/use-swr-key.test.tsx
FAIL test/use-swr-focus.test.tsx
  ● useSWR - focus › focusThrottleInterval should work

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `useSWR - focus focusThrottleInterval should work 2`

    Snapshot: "data: 1"
    Received: "data: 0"

      142 |     })
      143 | 
    > 144 |     expect(container.firstChild.textContent).toMatchInlineSnapshot(`"data: 1"`)
          |                                              ^
      145 |     fireEvent.focus(window)
      146 |     await act(() => {
      147 |       return sleep(1)

      at test/use-swr-focus.test.tsx:144:46
      at step (test/use-swr-focus.test.tsx:33:23)
      at Object.next (test/use-swr-focus.test.tsx:14:53)
      at fulfilled (test/use-swr-focus.test.tsx:5:58)

  ● useSWR - focus › focusThrottleInterval should work

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `useSWR - focus focusThrottleInterval should work 3`

    Snapshot: "data: 2"
    Received: "data: 1"

      148 |     })
      149 | 
    > 150 |     expect(container.firstChild.textContent).toMatchInlineSnapshot(`"data: 2"`)
          |                                              ^
      151 |   })
      152 | 
      153 |   it('focusThrottleInterval should be stateful', async () => {

      at test/use-swr-focus.test.tsx:150:46
      at step (test/use-swr-focus.test.tsx:33:23)
      at Object.next (test/use-swr-focus.test.tsx:14:53)
      at fulfilled (test/use-swr-focus.test.tsx:5:58)

 › 2 snapshots failed.
PASS test/use-swr-revalidate.test.tsx
PASS test/use-swr-configs.test.tsx
PASS test/use-swr-loading.test.tsx
PASS test/use-swr-cache.test.tsx
PASS test/use-swr-context-config.test.tsx

Snapshot Summary
 › 2 snapshots failed from 1 test suite. Inspect your code changes or run `yarn test -u` to update them.

Test Suites: 1 failed, 13 passed, 14 total
Tests:       1 failed, 95 passed, 96 total
Snapshots:   2 failed, 203 passed, 205 total
Time:        30.806s
Ran all test suites.
error Command failed with exit code 1.
```

## Expected Behavior

The test should be passed if code change doesn't break it. currently we need to re-run jobs when it's failed on github actions.

## Repro Steps / Code Example

N/A, observed it on github actions 

## Additional Context

N/A

**Comment by koba04** [comment]
I've created #944 to fix this.
