### ISSUE TITLE
During `next build` -> ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by tupizz** [vercel/swr#981]
# Bug report

## Description / Observed Behavior

Whenever I try to run `next build` in my project I got the following message:

```
> Build error occurred
ReferenceError: navigator is not defined
    at Object.641 (/Users/tadeutupinamba/Desktop/sparkbox/sparkbox-platform/node_modules/swr/dist/index.js:1:12630)
    at __webpack_require__ (/Users/tadeutupinamba/Desktop/sparkbox/sparkbox-platform/node_modules/swr/dist/index.js:1:154)
    at Object.516 (/Users/tadeutupinamba/Desktop/sparkbox/sparkbox-platform/node_modules/swr/dist/index.js:1:4302)
    at __webpack_require__ (/Users/tadeutupinamba/Desktop/sparkbox/sparkbox-platform/node_modules/swr/dist/index.js:1:154)
    at Object.325 (/Users/tadeutupinamba/Desktop/sparkbox/sparkbox-platform/node_modules/swr/dist/index.js:1:2305)
    at __webpack_require__ (/Users/tadeutupinamba/Desktop/sparkbox/sparkbox-platform/node_modules/swr/dist/index.js:1:154)
    at startup (/Users/tadeutupinamba/Desktop/sparkbox/sparkbox-platform/node_modules/swr/dist/index.js:1:291)
    at module.exports.48 (/Users/tadeutupinamba/Desktop/sparkbox/sparkbox-platform/node_modules/swr/dist/index.js:1:323)
    at Object.<anonymous> (/Users/tadeutupinamba/Desktop/sparkbox/sparkbox-platform/node_modules/swr/dist/index.js:1:333)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  type: 'ReferenceError'
}
```

I already tried to force the client side to render it only in the client-side, and therefore, correct the need of the `navigator` variable, but didn't work as well. 

## Expected Behavior

When I run `next build` should build the project correctly.

## Additional Context

SWR and next versions. 

```
"swr": "^0.4.2",
"next": "9.5.2",
```

**Comment by huozhi** [comment]
@tupizz do you have a minimal repro example link to share?

**Comment by tons613** [comment]
Any solution to this?

**Comment by shuding** [comment]
@tons613 Which version are you using?

**Comment by tons613** [comment]
> @tons613 Which version are you using?

I have resolved it. In my case I found out that the problem was not swr, but the problem was the webpack version
